# Generated by Django 4.0.4 on 2022-05-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=254)),
                ('upass', models.CharField(max_length=50)),
                ('udate', models.DateField()),
            ],
        ),
    ]
