# Generated by Django 4.0.4 on 2022-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDPUML', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.EmailField(max_length=254)),
                ('upass', models.CharField(max_length=50)),
            ],
        ),
    ]
