# Generated by Django 4.0.4 on 2022-05-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDPUML', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('s1', models.CharField(max_length=100)),
                ('s2', models.CharField(max_length=100)),
                ('s3', models.CharField(max_length=100)),
                ('s4', models.CharField(max_length=100)),
                ('s5', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('date1', models.CharField(max_length=100)),
            ],
        ),
    ]
